use std::fmt;

#[derive(Debug, Clone, Copy)]
pub enum Instruction {
  //Logical and arithmetic commands:
  ORA,
  AND,
  EOR,
  ADC,
  CMP,
  CPX,
  CPY,
  DEC,
  DEX,
  DEY,
  INC,
  INX,
  INY,
  ASL,
  ROL,
  LSR,
  ROR,
  //Move commands:
  LDA,
  STA,
  LDX,
  STX,
  LDY,
  STY,
  TAX,
  TXA,
  TAY,
  TYA,
  TSX,
  TXS,
  PLA,
  PHA,
  PLP,
  PHP,
  //Jump/Flag commands:
  BPL,
  BMI,
  BVC,
  BVS,
  BCC,
  BCS,
  BNE,
  BEQ,
  BRK,
  RTI,
  JSR,
  RTS,
  JMP,
  BIT,
  CLC,
  SEC,
  CLD,
  SED,
  CLI,
  SEI,
  CLV,
  NOP,
  //Illegal opcodes:
  SLO,
  RLA,
  SRE,
  RRA,
  SAX,
  DCP,
  ISC,
  ANC,
  ALR,
  ARR,
  XAA, //highly unstable
  LAX, //highly unstable
  AXS,
  SBC,
  AHX, //unstable
  SHY, //unstable
  SHX, //unstable
  TAS,
  LAS,
  KIL,
}

#[derive(Debug, Clone, Copy)]
pub enum OpMode {
  ACC,
  IMP,
  IMM,
  ZP0,
  ZPX,
  ZPY,
  IZX,
  IZY,
  ABS,
  ABX,
  ABY,
  IND,
  REL,
}

#[derive(Debug)]
pub enum LegalityType{
  Legal = 0,
  IllegalStable = 1,
  IllegalUnstable = 2,
  IllegalHighlyUnstable = 3,
  IllegalYolo,
}

#[derive(Debug)]
pub struct InstructionInfo {
  pub instr: Instruction,
  pub opcode: u8,
  pub mode: OpMode,
  pub cycles: u32,
  pub cycle_inc_pbc: bool,
  pub legality: LegalityType,
}

impl InstructionInfo {
  pub fn new() -> Self {
    Self {
      instr: Instruction::NOP,
      opcode: 0x0,
      mode: OpMode::IMP,
      cycles: 0,
      cycle_inc_pbc: false,
      legality: LegalityType::Legal,
    }
  }
}

impl fmt::Display for Instruction {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "{:?}", self)
  }
}

impl fmt::Display for InstructionInfo {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "{:?}", self)
  }
}

pub fn opcode_to_enum(opcode: u8) -> InstructionInfo {
  match opcode {
    0x00 => InstructionInfo{instr: Instruction::BRK, opcode: 0x00, mode: OpMode::IMP, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x01 => InstructionInfo{instr: Instruction::ORA, opcode: 0x01, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x02 => InstructionInfo{instr: Instruction::KIL, opcode: 0x02, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x03 => InstructionInfo{instr: Instruction::SLO, opcode: 0x03, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x04 => InstructionInfo{instr: Instruction::NOP, opcode: 0x04, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x05 => InstructionInfo{instr: Instruction::ORA, opcode: 0x05, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x06 => InstructionInfo{instr: Instruction::ASL, opcode: 0x06, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x07 => InstructionInfo{instr: Instruction::SLO, opcode: 0x07, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x08 => InstructionInfo{instr: Instruction::PHP, opcode: 0x08, mode: OpMode::IMP, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x09 => InstructionInfo{instr: Instruction::ORA, opcode: 0x09, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x0A => InstructionInfo{instr: Instruction::ASL, opcode: 0x0A, mode: OpMode::ACC, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x0B => InstructionInfo{instr: Instruction::ANC, opcode: 0x0B, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x0C => InstructionInfo{instr: Instruction::NOP, opcode: 0x0C, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x0D => InstructionInfo{instr: Instruction::ORA, opcode: 0x0D, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x0E => InstructionInfo{instr: Instruction::ASL, opcode: 0x0E, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x0F => InstructionInfo{instr: Instruction::SLO, opcode: 0x0F, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x10 => InstructionInfo{instr: Instruction::BPL, opcode: 0x10, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x11 => InstructionInfo{instr: Instruction::ORA, opcode: 0x11, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x12 => InstructionInfo{instr: Instruction::KIL, opcode: 0x12, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x13 => InstructionInfo{instr: Instruction::SLO, opcode: 0x13, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x14 => InstructionInfo{instr: Instruction::NOP, opcode: 0x14, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x15 => InstructionInfo{instr: Instruction::ORA, opcode: 0x15, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x16 => InstructionInfo{instr: Instruction::ASL, opcode: 0x16, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x17 => InstructionInfo{instr: Instruction::SLO, opcode: 0x17, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x18 => InstructionInfo{instr: Instruction::CLC, opcode: 0x18, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x19 => InstructionInfo{instr: Instruction::ORA, opcode: 0x19, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x1A => InstructionInfo{instr: Instruction::NOP, opcode: 0x1A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x1B => InstructionInfo{instr: Instruction::SLO, opcode: 0x1B, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x1C => InstructionInfo{instr: Instruction::NOP, opcode: 0x1C, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0x1D => InstructionInfo{instr: Instruction::ORA, opcode: 0x1D, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x1E => InstructionInfo{instr: Instruction::ASL, opcode: 0x1E, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x1F => InstructionInfo{instr: Instruction::SLO, opcode: 0x1F, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x20 => InstructionInfo{instr: Instruction::JSR, opcode: 0x20, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x21 => InstructionInfo{instr: Instruction::AND, opcode: 0x21, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x22 => InstructionInfo{instr: Instruction::KIL, opcode: 0x22, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x23 => InstructionInfo{instr: Instruction::RLA, opcode: 0x23, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x24 => InstructionInfo{instr: Instruction::BIT, opcode: 0x24, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x25 => InstructionInfo{instr: Instruction::AND, opcode: 0x25, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x26 => InstructionInfo{instr: Instruction::ROL, opcode: 0x26, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x27 => InstructionInfo{instr: Instruction::RLA, opcode: 0x27, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x28 => InstructionInfo{instr: Instruction::PLP, opcode: 0x28, mode: OpMode::IMP, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x29 => InstructionInfo{instr: Instruction::AND, opcode: 0x29, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x2A => InstructionInfo{instr: Instruction::ROL, opcode: 0x2A, mode: OpMode::ACC, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x2B => InstructionInfo{instr: Instruction::ANC, opcode: 0x2B, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x2C => InstructionInfo{instr: Instruction::BIT, opcode: 0x2C, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x2D => InstructionInfo{instr: Instruction::AND, opcode: 0x2D, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x2E => InstructionInfo{instr: Instruction::ROL, opcode: 0x2E, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x2F => InstructionInfo{instr: Instruction::RLA, opcode: 0x2F, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x30 => InstructionInfo{instr: Instruction::BMI, opcode: 0x30, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x31 => InstructionInfo{instr: Instruction::AND, opcode: 0x31, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x32 => InstructionInfo{instr: Instruction::KIL, opcode: 0x32, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x33 => InstructionInfo{instr: Instruction::RLA, opcode: 0x33, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x34 => InstructionInfo{instr: Instruction::NOP, opcode: 0x34, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x35 => InstructionInfo{instr: Instruction::AND, opcode: 0x35, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x36 => InstructionInfo{instr: Instruction::ROL, opcode: 0x36, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x37 => InstructionInfo{instr: Instruction::RLA, opcode: 0x37, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x38 => InstructionInfo{instr: Instruction::SEC, opcode: 0x38, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x39 => InstructionInfo{instr: Instruction::AND, opcode: 0x39, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x3A => InstructionInfo{instr: Instruction::NOP, opcode: 0x3A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x3B => InstructionInfo{instr: Instruction::RLA, opcode: 0x3B, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x3C => InstructionInfo{instr: Instruction::NOP, opcode: 0x3C, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0x3D => InstructionInfo{instr: Instruction::AND, opcode: 0x3D, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x3E => InstructionInfo{instr: Instruction::ROL, opcode: 0x3E, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x3F => InstructionInfo{instr: Instruction::RLA, opcode: 0x3F, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x40 => InstructionInfo{instr: Instruction::RTI, opcode: 0x40, mode: OpMode::IMP, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x41 => InstructionInfo{instr: Instruction::EOR, opcode: 0x41, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x42 => InstructionInfo{instr: Instruction::KIL, opcode: 0x42, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x43 => InstructionInfo{instr: Instruction::SRE, opcode: 0x43, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x44 => InstructionInfo{instr: Instruction::NOP, opcode: 0x44, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x45 => InstructionInfo{instr: Instruction::EOR, opcode: 0x45, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x46 => InstructionInfo{instr: Instruction::LSR, opcode: 0x46, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x47 => InstructionInfo{instr: Instruction::SRE, opcode: 0x47, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x48 => InstructionInfo{instr: Instruction::PHA, opcode: 0x48, mode: OpMode::IMP, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x49 => InstructionInfo{instr: Instruction::EOR, opcode: 0x49, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x4A => InstructionInfo{instr: Instruction::LSR, opcode: 0x4A, mode: OpMode::ACC, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x4B => InstructionInfo{instr: Instruction::ALR, opcode: 0x4B, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x4C => InstructionInfo{instr: Instruction::JMP, opcode: 0x4C, mode: OpMode::ABS, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x4D => InstructionInfo{instr: Instruction::EOR, opcode: 0x4D, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x4E => InstructionInfo{instr: Instruction::LSR, opcode: 0x4E, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x4F => InstructionInfo{instr: Instruction::SRE, opcode: 0x4F, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x50 => InstructionInfo{instr: Instruction::BVC, opcode: 0x50, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x51 => InstructionInfo{instr: Instruction::EOR, opcode: 0x51, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x52 => InstructionInfo{instr: Instruction::KIL, opcode: 0x52, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x53 => InstructionInfo{instr: Instruction::SRE, opcode: 0x53, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x54 => InstructionInfo{instr: Instruction::NOP, opcode: 0x54, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x55 => InstructionInfo{instr: Instruction::EOR, opcode: 0x55, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x56 => InstructionInfo{instr: Instruction::LSR, opcode: 0x56, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x57 => InstructionInfo{instr: Instruction::SRE, opcode: 0x57, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x58 => InstructionInfo{instr: Instruction::CLI, opcode: 0x58, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x59 => InstructionInfo{instr: Instruction::EOR, opcode: 0x59, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x5A => InstructionInfo{instr: Instruction::NOP, opcode: 0x5A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x5B => InstructionInfo{instr: Instruction::SRE, opcode: 0x5B, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x5C => InstructionInfo{instr: Instruction::NOP, opcode: 0x5C, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0x5D => InstructionInfo{instr: Instruction::EOR, opcode: 0x5D, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x5E => InstructionInfo{instr: Instruction::LSR, opcode: 0x5E, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x5F => InstructionInfo{instr: Instruction::SRE, opcode: 0x5F, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x60 => InstructionInfo{instr: Instruction::RTS, opcode: 0x60, mode: OpMode::IMP, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x61 => InstructionInfo{instr: Instruction::ADC, opcode: 0x61, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x62 => InstructionInfo{instr: Instruction::KIL, opcode: 0x62, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x63 => InstructionInfo{instr: Instruction::RRA, opcode: 0x63, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x64 => InstructionInfo{instr: Instruction::NOP, opcode: 0x64, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x65 => InstructionInfo{instr: Instruction::ADC, opcode: 0x65, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x66 => InstructionInfo{instr: Instruction::ROR, opcode: 0x66, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x67 => InstructionInfo{instr: Instruction::RRA, opcode: 0x67, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x68 => InstructionInfo{instr: Instruction::PLA, opcode: 0x68, mode: OpMode::IMP, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x69 => InstructionInfo{instr: Instruction::ADC, opcode: 0x69, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x6A => InstructionInfo{instr: Instruction::ROR, opcode: 0x6A, mode: OpMode::ACC, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x6B => InstructionInfo{instr: Instruction::ARR, opcode: 0x6B, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x6C => InstructionInfo{instr: Instruction::JMP, opcode: 0x6C, mode: OpMode::IND, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x6D => InstructionInfo{instr: Instruction::ADC, opcode: 0x6D, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x6E => InstructionInfo{instr: Instruction::ROR, opcode: 0x6E, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x6F => InstructionInfo{instr: Instruction::RRA, opcode: 0x6F, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x70 => InstructionInfo{instr: Instruction::BVS, opcode: 0x70, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x71 => InstructionInfo{instr: Instruction::ADC, opcode: 0x71, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x72 => InstructionInfo{instr: Instruction::KIL, opcode: 0x72, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x73 => InstructionInfo{instr: Instruction::RRA, opcode: 0x73, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x74 => InstructionInfo{instr: Instruction::NOP, opcode: 0x74, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x75 => InstructionInfo{instr: Instruction::ADC, opcode: 0x75, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x76 => InstructionInfo{instr: Instruction::ROR, opcode: 0x76, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x77 => InstructionInfo{instr: Instruction::RRA, opcode: 0x77, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x78 => InstructionInfo{instr: Instruction::SEI, opcode: 0x78, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x79 => InstructionInfo{instr: Instruction::ADC, opcode: 0x79, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x7A => InstructionInfo{instr: Instruction::NOP, opcode: 0x7A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x7B => InstructionInfo{instr: Instruction::RRA, opcode: 0x7B, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x7C => InstructionInfo{instr: Instruction::NOP, opcode: 0x7C, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0x7D => InstructionInfo{instr: Instruction::ADC, opcode: 0x7D, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x7E => InstructionInfo{instr: Instruction::ROR, opcode: 0x7E, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x7F => InstructionInfo{instr: Instruction::RRA, opcode: 0x7F, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x80 => InstructionInfo{instr: Instruction::NOP, opcode: 0x80, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x81 => InstructionInfo{instr: Instruction::STA, opcode: 0x81, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x82 => InstructionInfo{instr: Instruction::NOP, opcode: 0x82, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x83 => InstructionInfo{instr: Instruction::SAX, opcode: 0x83, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x84 => InstructionInfo{instr: Instruction::STY, opcode: 0x84, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x85 => InstructionInfo{instr: Instruction::STA, opcode: 0x85, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x86 => InstructionInfo{instr: Instruction::STX, opcode: 0x86, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x87 => InstructionInfo{instr: Instruction::SAX, opcode: 0x87, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x88 => InstructionInfo{instr: Instruction::DEY, opcode: 0x88, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x89 => InstructionInfo{instr: Instruction::NOP, opcode: 0x89, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x8A => InstructionInfo{instr: Instruction::TXA, opcode: 0x8A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x8B => InstructionInfo{instr: Instruction::XAA, opcode: 0x8B, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalHighlyUnstable},
    0x8C => InstructionInfo{instr: Instruction::STY, opcode: 0x8C, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x8D => InstructionInfo{instr: Instruction::STA, opcode: 0x8D, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x8E => InstructionInfo{instr: Instruction::STX, opcode: 0x8E, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x8F => InstructionInfo{instr: Instruction::SAX, opcode: 0x8F, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0x90 => InstructionInfo{instr: Instruction::BCC, opcode: 0x90, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0x91 => InstructionInfo{instr: Instruction::STA, opcode: 0x91, mode: OpMode::IZY, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x92 => InstructionInfo{instr: Instruction::KIL, opcode: 0x92, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x93 => InstructionInfo{instr: Instruction::AHX, opcode: 0x93, mode: OpMode::IZY, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable},
    0x94 => InstructionInfo{instr: Instruction::STY, opcode: 0x94, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x95 => InstructionInfo{instr: Instruction::STA, opcode: 0x95, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x96 => InstructionInfo{instr: Instruction::STX, opcode: 0x96, mode: OpMode::ZPY, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x97 => InstructionInfo{instr: Instruction::SAX, opcode: 0x97, mode: OpMode::ZPY, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0x98 => InstructionInfo{instr: Instruction::TYA, opcode: 0x98, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x99 => InstructionInfo{instr: Instruction::STA, opcode: 0x99, mode: OpMode::ABY, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x9A => InstructionInfo{instr: Instruction::TXS, opcode: 0x9A, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x9B => InstructionInfo{instr: Instruction::TAS, opcode: 0x9B, mode: OpMode::ABY, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable},
    0x9C => InstructionInfo{instr: Instruction::SHY, opcode: 0x9C, mode: OpMode::ABX, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable},
    0x9D => InstructionInfo{instr: Instruction::STA, opcode: 0x9D, mode: OpMode::ABX, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0x9E => InstructionInfo{instr: Instruction::SHX, opcode: 0x9E, mode: OpMode::ABY, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable},
    0x9F => InstructionInfo{instr: Instruction::AHX, opcode: 0x9F, mode: OpMode::ABY, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable},

    0xA0 => InstructionInfo{instr: Instruction::LDY, opcode: 0xA0, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA1 => InstructionInfo{instr: Instruction::LDA, opcode: 0xA1, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA2 => InstructionInfo{instr: Instruction::LDX, opcode: 0xA2, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA3 => InstructionInfo{instr: Instruction::LAX, opcode: 0xA3, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xA4 => InstructionInfo{instr: Instruction::LDY, opcode: 0xA4, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA5 => InstructionInfo{instr: Instruction::LDA, opcode: 0xA5, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA6 => InstructionInfo{instr: Instruction::LDX, opcode: 0xA6, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA7 => InstructionInfo{instr: Instruction::LAX, opcode: 0xA7, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xA8 => InstructionInfo{instr: Instruction::TAY, opcode: 0xA8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xA9 => InstructionInfo{instr: Instruction::LDA, opcode: 0xA9, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xAA => InstructionInfo{instr: Instruction::TAX, opcode: 0xAA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xAB => InstructionInfo{instr: Instruction::LAX, opcode: 0xAB, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalHighlyUnstable},
    0xAC => InstructionInfo{instr: Instruction::LDY, opcode: 0xAC, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xAD => InstructionInfo{instr: Instruction::LDA, opcode: 0xAD, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xAE => InstructionInfo{instr: Instruction::LDX, opcode: 0xAE, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xAF => InstructionInfo{instr: Instruction::LAX, opcode: 0xAF, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0xB0 => InstructionInfo{instr: Instruction::BCS, opcode: 0xB0, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xB1 => InstructionInfo{instr: Instruction::LDA, opcode: 0xB1, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xB2 => InstructionInfo{instr: Instruction::KIL, opcode: 0xB2, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xB3 => InstructionInfo{instr: Instruction::LAX, opcode: 0xB3, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0xB4 => InstructionInfo{instr: Instruction::LDY, opcode: 0xB4, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xB5 => InstructionInfo{instr: Instruction::LDA, opcode: 0xB5, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xB6 => InstructionInfo{instr: Instruction::LDX, opcode: 0xB6, mode: OpMode::ZPY, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xB7 => InstructionInfo{instr: Instruction::LAX, opcode: 0xB7, mode: OpMode::ZPY, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xB8 => InstructionInfo{instr: Instruction::CLV, opcode: 0xB8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xB9 => InstructionInfo{instr: Instruction::LDA, opcode: 0xB9, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xBA => InstructionInfo{instr: Instruction::TSX, opcode: 0xBA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xBB => InstructionInfo{instr: Instruction::LAS, opcode: 0xBB, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0xBC => InstructionInfo{instr: Instruction::LDY, opcode: 0xBC, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xBD => InstructionInfo{instr: Instruction::LDA, opcode: 0xBD, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xBE => InstructionInfo{instr: Instruction::LDX, opcode: 0xBE, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xBF => InstructionInfo{instr: Instruction::LAX, opcode: 0xBF, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},

    0xC0 => InstructionInfo{instr: Instruction::CPY, opcode: 0xC0, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC1 => InstructionInfo{instr: Instruction::CMP, opcode: 0xC1, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC2 => InstructionInfo{instr: Instruction::NOP, opcode: 0xC2, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xC3 => InstructionInfo{instr: Instruction::DCP, opcode: 0xC3, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xC4 => InstructionInfo{instr: Instruction::CPY, opcode: 0xC4, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC5 => InstructionInfo{instr: Instruction::CMP, opcode: 0xC5, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC6 => InstructionInfo{instr: Instruction::DEC, opcode: 0xC6, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC7 => InstructionInfo{instr: Instruction::DCP, opcode: 0xC7, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xC8 => InstructionInfo{instr: Instruction::INY, opcode: 0xC8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xC9 => InstructionInfo{instr: Instruction::CMP, opcode: 0xC9, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xCA => InstructionInfo{instr: Instruction::DEX, opcode: 0xCA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xCB => InstructionInfo{instr: Instruction::AXS, opcode: 0xCB, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xCC => InstructionInfo{instr: Instruction::CPY, opcode: 0xCC, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xCD => InstructionInfo{instr: Instruction::CMP, opcode: 0xCD, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xCE => InstructionInfo{instr: Instruction::DEC, opcode: 0xCE, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xCF => InstructionInfo{instr: Instruction::DCP, opcode: 0xCF, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0xD0 => InstructionInfo{instr: Instruction::BNE, opcode: 0xD0, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xD1 => InstructionInfo{instr: Instruction::CMP, opcode: 0xD1, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xD2 => InstructionInfo{instr: Instruction::KIL, opcode: 0xD2, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xD3 => InstructionInfo{instr: Instruction::DCP, opcode: 0xD3, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xD4 => InstructionInfo{instr: Instruction::NOP, opcode: 0xD4, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xD5 => InstructionInfo{instr: Instruction::CMP, opcode: 0xD5, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xD6 => InstructionInfo{instr: Instruction::DEC, opcode: 0xD6, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xD7 => InstructionInfo{instr: Instruction::DCP, opcode: 0xD7, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xD8 => InstructionInfo{instr: Instruction::CLD, opcode: 0xD8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xD9 => InstructionInfo{instr: Instruction::CMP, opcode: 0xD9, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xDA => InstructionInfo{instr: Instruction::NOP, opcode: 0xDA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xDB => InstructionInfo{instr: Instruction::DCP, opcode: 0xDB, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xDC => InstructionInfo{instr: Instruction::NOP, opcode: 0xDC, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0xDD => InstructionInfo{instr: Instruction::CMP, opcode: 0xDD, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xDE => InstructionInfo{instr: Instruction::DEC, opcode: 0xDE, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xDF => InstructionInfo{instr: Instruction::DCP, opcode: 0xDF, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0xE0 => InstructionInfo{instr: Instruction::CPX, opcode: 0xE0, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE1 => InstructionInfo{instr: Instruction::SBC, opcode: 0xE1, mode: OpMode::IZX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE2 => InstructionInfo{instr: Instruction::NOP, opcode: 0xE2, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xE3 => InstructionInfo{instr: Instruction::ISC, opcode: 0xE3, mode: OpMode::IZX, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xE4 => InstructionInfo{instr: Instruction::CPX, opcode: 0xE4, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE5 => InstructionInfo{instr: Instruction::SBC, opcode: 0xE5, mode: OpMode::ZP0, cycles: 3, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE6 => InstructionInfo{instr: Instruction::INC, opcode: 0xE6, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE7 => InstructionInfo{instr: Instruction::ISC, opcode: 0xE7, mode: OpMode::ZP0, cycles: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xE8 => InstructionInfo{instr: Instruction::INX, opcode: 0xE8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xE9 => InstructionInfo{instr: Instruction::SBC, opcode: 0xE9, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xEA => InstructionInfo{instr: Instruction::NOP, opcode: 0xEA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xEB => InstructionInfo{instr: Instruction::SBC, opcode: 0xEB, mode: OpMode::IMM, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xEC => InstructionInfo{instr: Instruction::CPX, opcode: 0xEC, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xED => InstructionInfo{instr: Instruction::SBC, opcode: 0xED, mode: OpMode::ABS, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xEE => InstructionInfo{instr: Instruction::INC, opcode: 0xEE, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xEF => InstructionInfo{instr: Instruction::ISC, opcode: 0xEF, mode: OpMode::ABS, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},

    0xF0 => InstructionInfo{instr: Instruction::BEQ, opcode: 0xF0, mode: OpMode::REL, cycles: 2, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xF1 => InstructionInfo{instr: Instruction::SBC, opcode: 0xF1, mode: OpMode::IZY, cycles: 5, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xF2 => InstructionInfo{instr: Instruction::KIL, opcode: 0xF2, mode: OpMode::IMP, cycles: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xF3 => InstructionInfo{instr: Instruction::ISC, opcode: 0xF3, mode: OpMode::IZY, cycles: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xF4 => InstructionInfo{instr: Instruction::NOP, opcode: 0xF4, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xF5 => InstructionInfo{instr: Instruction::SBC, opcode: 0xF5, mode: OpMode::ZPX, cycles: 4, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xF6 => InstructionInfo{instr: Instruction::INC, opcode: 0xF6, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xF7 => InstructionInfo{instr: Instruction::ISC, opcode: 0xF7, mode: OpMode::ZPX, cycles: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xF8 => InstructionInfo{instr: Instruction::SED, opcode: 0xF8, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xF9 => InstructionInfo{instr: Instruction::SBC, opcode: 0xF9, mode: OpMode::ABY, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xFA => InstructionInfo{instr: Instruction::NOP, opcode: 0xFA, mode: OpMode::IMP, cycles: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xFB => InstructionInfo{instr: Instruction::ISC, opcode: 0xFB, mode: OpMode::ABY, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
    0xFC => InstructionInfo{instr: Instruction::NOP, opcode: 0xFC, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable},
    0xFD => InstructionInfo{instr: Instruction::SBC, opcode: 0xFD, mode: OpMode::ABX, cycles: 4, cycle_inc_pbc: true, legality: LegalityType::Legal},
    0xFE => InstructionInfo{instr: Instruction::INC, opcode: 0xFE, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::Legal},
    0xFF => InstructionInfo{instr: Instruction::ISC, opcode: 0xFF, mode: OpMode::ABX, cycles: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable},
  }
}
