use std::fmt;

#[derive(Debug)]
pub enum OpMode {
  IMP,
  IMM,
  ZP,
  ZPX,
  ZPY,
  IZX,
  IZY,
  ABS,
  ABX,
  ABY,
  IND,
  REL,
}

#[derive(Debug)]
pub enum LegalityType{
  Legal = 0,
  IllegalStable = 1,
  IllegalUnstable = 2,
  IllegalHighlyUnstable = 3,
  IllegalYolo,
}

#[derive(Debug)]
pub struct InstructionInfo{
  pub opcode: u8,
  pub mode: OpMode,
  pub cycle: i32,
  pub cycle_inc_pbc: bool,
  pub legality: LegalityType,
}

#[derive(Debug)]
pub enum Instruction {
  //Logical and arithmetic commands:
  ORA,
  AND,
  EOR,
  ADC,
  CMP,
  CPX,
  CPY,
  DEC,
  DEX,
  DEY,
  INC,
  INX,
  INY,
  ASL,
  ROL,
  LSR,
  ROR,
  //Move commands:
  LDA,
  STA,
  LDX,
  STX,
  LDY,
  STY,
  TAX,
  TXA,
  TAY,
  TYA,
  TSX,
  TXS,
  PLA,
  PHA,
  PLP,
  PHP,
  //Jump/Flag commands:
  BPL,
  BMI,
  BVC,
  BVS,
  BCC,
  BCS,
  BNE,
  BEQ,
  BRK,
  RTI,
  JSR,
  RTS,
  JMP,
  BIT,
  CLC,
  SEC,
  CLD,
  SED,
  CLI,
  SEI,
  CLV,
  NOP,
  //Illegal opcodes:
  SLO,
  RLA,
  SRE,
  RRA,
  SAX,
  DCP,
  ISC,
  ANC,
  ALR,
  ARR,
  XAA, //highly unstable
  LAX, //highly unstable
  AXS,
  SBC,
  AHX, //unstable
  SHY, //unstable
  SHX, //unstable
  TAS,
  LAS,
  KIL,
}

impl fmt::Display for Instruction {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "{:?}", self)
  }
}

impl fmt::Display for InstructionInfo {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "{:?}", self)
  }
}

pub fn opcode_to_enum(opcode: u8) -> (Instruction, InstructionInfo) {
  match opcode {
    0x00 => (Instruction::BRK, InstructionInfo{opcode: 0x00, mode: OpMode::IMP, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x01 => (Instruction::ORA, InstructionInfo{opcode: 0x01, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x02 => (Instruction::KIL, InstructionInfo{opcode: 0x02, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x03 => (Instruction::SLO, InstructionInfo{opcode: 0x03, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x04 => (Instruction::NOP, InstructionInfo{opcode: 0x04, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x05 => (Instruction::ORA, InstructionInfo{opcode: 0x05, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x06 => (Instruction::ASL, InstructionInfo{opcode: 0x06, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x07 => (Instruction::SLO, InstructionInfo{opcode: 0x07, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x08 => (Instruction::PHP, InstructionInfo{opcode: 0x08, mode: OpMode::IMP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x09 => (Instruction::ORA, InstructionInfo{opcode: 0x09, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x0A => (Instruction::ASL, InstructionInfo{opcode: 0x0A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x0B => (Instruction::ANC, InstructionInfo{opcode: 0x0B, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x0C => (Instruction::NOP, InstructionInfo{opcode: 0x0C, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x0D => (Instruction::ORA, InstructionInfo{opcode: 0x0D, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x0E => (Instruction::ASL, InstructionInfo{opcode: 0x0E, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x0F => (Instruction::SLO, InstructionInfo{opcode: 0x0F, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x10 => (Instruction::BPL, InstructionInfo{opcode: 0x10, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x11 => (Instruction::ORA, InstructionInfo{opcode: 0x11, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x12 => (Instruction::KIL, InstructionInfo{opcode: 0x12, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x13 => (Instruction::SLO, InstructionInfo{opcode: 0x13, mode: OpMode::IZY, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x14 => (Instruction::NOP, InstructionInfo{opcode: 0x14, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x15 => (Instruction::ORA, InstructionInfo{opcode: 0x15, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x16 => (Instruction::ASL, InstructionInfo{opcode: 0x16, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x17 => (Instruction::SLO, InstructionInfo{opcode: 0x17, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x18 => (Instruction::CLC, InstructionInfo{opcode: 0x18, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x19 => (Instruction::ORA, InstructionInfo{opcode: 0x19, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x1A => (Instruction::NOP, InstructionInfo{opcode: 0x1A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x1B => (Instruction::SLO, InstructionInfo{opcode: 0x1B, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x1C => (Instruction::NOP, InstructionInfo{opcode: 0x1C, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0x1D => (Instruction::ORA, InstructionInfo{opcode: 0x1D, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x1E => (Instruction::ASL, InstructionInfo{opcode: 0x1E, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x1F => (Instruction::SLO, InstructionInfo{opcode: 0x1F, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x20 => (Instruction::JSR, InstructionInfo{opcode: 0x20, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x21 => (Instruction::AND, InstructionInfo{opcode: 0x21, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x22 => (Instruction::KIL, InstructionInfo{opcode: 0x22, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x23 => (Instruction::RLA, InstructionInfo{opcode: 0x23, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x24 => (Instruction::BIT, InstructionInfo{opcode: 0x24, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x25 => (Instruction::AND, InstructionInfo{opcode: 0x25, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x26 => (Instruction::ROL, InstructionInfo{opcode: 0x26, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x27 => (Instruction::RLA, InstructionInfo{opcode: 0x27, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x28 => (Instruction::PLP, InstructionInfo{opcode: 0x28, mode: OpMode::IMP, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x29 => (Instruction::AND, InstructionInfo{opcode: 0x29, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x2A => (Instruction::ROL, InstructionInfo{opcode: 0x2A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x2B => (Instruction::ANC, InstructionInfo{opcode: 0x2B, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x2C => (Instruction::BIT, InstructionInfo{opcode: 0x2C, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x2D => (Instruction::AND, InstructionInfo{opcode: 0x2D, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x2E => (Instruction::ROL, InstructionInfo{opcode: 0x2E, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x2F => (Instruction::RLA, InstructionInfo{opcode: 0x2F, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x30 => (Instruction::BMI, InstructionInfo{opcode: 0x30, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x31 => (Instruction::AND, InstructionInfo{opcode: 0x31, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x32 => (Instruction::KIL, InstructionInfo{opcode: 0x32, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x33 => (Instruction::RLA, InstructionInfo{opcode: 0x33, mode: OpMode::IZY, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x34 => (Instruction::NOP, InstructionInfo{opcode: 0x34, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x35 => (Instruction::AND, InstructionInfo{opcode: 0x35, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x36 => (Instruction::ROL, InstructionInfo{opcode: 0x36, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x37 => (Instruction::RLA, InstructionInfo{opcode: 0x37, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x38 => (Instruction::SEC, InstructionInfo{opcode: 0x38, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x39 => (Instruction::AND, InstructionInfo{opcode: 0x39, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x3A => (Instruction::NOP, InstructionInfo{opcode: 0x3A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x3B => (Instruction::RLA, InstructionInfo{opcode: 0x3B, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x3C => (Instruction::NOP, InstructionInfo{opcode: 0x3C, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0x3D => (Instruction::AND, InstructionInfo{opcode: 0x3D, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x3E => (Instruction::ROL, InstructionInfo{opcode: 0x3E, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x3F => (Instruction::RLA, InstructionInfo{opcode: 0x3F, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x40 => (Instruction::RTI, InstructionInfo{opcode: 0x40, mode: OpMode::IMP, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x41 => (Instruction::EOR, InstructionInfo{opcode: 0x41, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x42 => (Instruction::KIL, InstructionInfo{opcode: 0x42, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x43 => (Instruction::SRE, InstructionInfo{opcode: 0x43, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x44 => (Instruction::NOP, InstructionInfo{opcode: 0x44, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x45 => (Instruction::EOR, InstructionInfo{opcode: 0x45, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x46 => (Instruction::LSR, InstructionInfo{opcode: 0x46, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x47 => (Instruction::SRE, InstructionInfo{opcode: 0x47, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x48 => (Instruction::PHA, InstructionInfo{opcode: 0x48, mode: OpMode::IMP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x49 => (Instruction::EOR, InstructionInfo{opcode: 0x49, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x4A => (Instruction::LSR, InstructionInfo{opcode: 0x4A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x4B => (Instruction::ALR, InstructionInfo{opcode: 0x4B, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x4C => (Instruction::JMP, InstructionInfo{opcode: 0x4C, mode: OpMode::ABS, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x4D => (Instruction::EOR, InstructionInfo{opcode: 0x4D, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x4E => (Instruction::LSR, InstructionInfo{opcode: 0x4E, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x4F => (Instruction::SRE, InstructionInfo{opcode: 0x4F, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x50 => (Instruction::BVC, InstructionInfo{opcode: 0x50, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x51 => (Instruction::EOR, InstructionInfo{opcode: 0x51, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x52 => (Instruction::KIL, InstructionInfo{opcode: 0x52, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x53 => (Instruction::SRE, InstructionInfo{opcode: 0x53, mode: OpMode::IZY, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x54 => (Instruction::NOP, InstructionInfo{opcode: 0x54, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x55 => (Instruction::EOR, InstructionInfo{opcode: 0x55, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x56 => (Instruction::LSR, InstructionInfo{opcode: 0x56, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x57 => (Instruction::SRE, InstructionInfo{opcode: 0x57, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x58 => (Instruction::CLI, InstructionInfo{opcode: 0x58, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x59 => (Instruction::EOR, InstructionInfo{opcode: 0x59, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x5A => (Instruction::NOP, InstructionInfo{opcode: 0x5A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x5B => (Instruction::SRE, InstructionInfo{opcode: 0x5B, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x5C => (Instruction::NOP, InstructionInfo{opcode: 0x5C, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0x5D => (Instruction::EOR, InstructionInfo{opcode: 0x5D, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x5E => (Instruction::LSR, InstructionInfo{opcode: 0x5E, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x5F => (Instruction::SRE, InstructionInfo{opcode: 0x5F, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x60 => (Instruction::RTS, InstructionInfo{opcode: 0x60, mode: OpMode::IMP, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x61 => (Instruction::ADC, InstructionInfo{opcode: 0x61, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x62 => (Instruction::KIL, InstructionInfo{opcode: 0x62, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x63 => (Instruction::RRA, InstructionInfo{opcode: 0x63, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x64 => (Instruction::NOP, InstructionInfo{opcode: 0x64, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x65 => (Instruction::ADC, InstructionInfo{opcode: 0x65, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x66 => (Instruction::ROR, InstructionInfo{opcode: 0x66, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x67 => (Instruction::RRA, InstructionInfo{opcode: 0x67, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x68 => (Instruction::PLA, InstructionInfo{opcode: 0x68, mode: OpMode::IMP, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x69 => (Instruction::ADC, InstructionInfo{opcode: 0x69, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x6A => (Instruction::ROR, InstructionInfo{opcode: 0x6A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x6B => (Instruction::ARR, InstructionInfo{opcode: 0x6B, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x6C => (Instruction::JMP, InstructionInfo{opcode: 0x6C, mode: OpMode::IND, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x6D => (Instruction::ADC, InstructionInfo{opcode: 0x6D, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x6E => (Instruction::ROR, InstructionInfo{opcode: 0x6E, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x6F => (Instruction::RRA, InstructionInfo{opcode: 0x6F, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x70 => (Instruction::BVS, InstructionInfo{opcode: 0x70, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x71 => (Instruction::ADC, InstructionInfo{opcode: 0x71, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x72 => (Instruction::KIL, InstructionInfo{opcode: 0x72, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x73 => (Instruction::RRA, InstructionInfo{opcode: 0x73, mode: OpMode::IZY, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x74 => (Instruction::NOP, InstructionInfo{opcode: 0x74, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x75 => (Instruction::ADC, InstructionInfo{opcode: 0x75, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x76 => (Instruction::ROR, InstructionInfo{opcode: 0x76, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x77 => (Instruction::RRA, InstructionInfo{opcode: 0x77, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x78 => (Instruction::SEI, InstructionInfo{opcode: 0x78, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x79 => (Instruction::ADC, InstructionInfo{opcode: 0x79, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x7A => (Instruction::NOP, InstructionInfo{opcode: 0x7A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x7B => (Instruction::RRA, InstructionInfo{opcode: 0x7B, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x7C => (Instruction::NOP, InstructionInfo{opcode: 0x7C, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0x7D => (Instruction::ADC, InstructionInfo{opcode: 0x7D, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x7E => (Instruction::ROR, InstructionInfo{opcode: 0x7E, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x7F => (Instruction::RRA, InstructionInfo{opcode: 0x7F, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x80 => (Instruction::NOP, InstructionInfo{opcode: 0x80, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x81 => (Instruction::STA, InstructionInfo{opcode: 0x81, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x82 => (Instruction::NOP, InstructionInfo{opcode: 0x82, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x83 => (Instruction::SAX, InstructionInfo{opcode: 0x83, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x84 => (Instruction::STY, InstructionInfo{opcode: 0x84, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x85 => (Instruction::STA, InstructionInfo{opcode: 0x85, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x86 => (Instruction::STX, InstructionInfo{opcode: 0x86, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x87 => (Instruction::SAX, InstructionInfo{opcode: 0x87, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x88 => (Instruction::DEY, InstructionInfo{opcode: 0x88, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x89 => (Instruction::NOP, InstructionInfo{opcode: 0x89, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x8A => (Instruction::TXA, InstructionInfo{opcode: 0x8A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x8B => (Instruction::XAA, InstructionInfo{opcode: 0x8B, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalHighlyUnstable}),
    0x8C => (Instruction::STY, InstructionInfo{opcode: 0x8C, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x8D => (Instruction::STA, InstructionInfo{opcode: 0x8D, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x8E => (Instruction::STX, InstructionInfo{opcode: 0x8E, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x8F => (Instruction::SAX, InstructionInfo{opcode: 0x8F, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0x90 => (Instruction::BCC, InstructionInfo{opcode: 0x90, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0x91 => (Instruction::STA, InstructionInfo{opcode: 0x91, mode: OpMode::IZY, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x92 => (Instruction::KIL, InstructionInfo{opcode: 0x92, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x93 => (Instruction::AHX, InstructionInfo{opcode: 0x93, mode: OpMode::IZY, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable}),
    0x94 => (Instruction::STY, InstructionInfo{opcode: 0x94, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x95 => (Instruction::STA, InstructionInfo{opcode: 0x95, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x96 => (Instruction::STX, InstructionInfo{opcode: 0x96, mode: OpMode::ZPY, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x97 => (Instruction::SAX, InstructionInfo{opcode: 0x97, mode: OpMode::ZPY, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0x98 => (Instruction::TYA, InstructionInfo{opcode: 0x98, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x99 => (Instruction::STA, InstructionInfo{opcode: 0x99, mode: OpMode::ABY, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x9A => (Instruction::TXS, InstructionInfo{opcode: 0x9A, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x9B => (Instruction::TAS, InstructionInfo{opcode: 0x9B, mode: OpMode::ABY, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable}),
    0x9C => (Instruction::SHY, InstructionInfo{opcode: 0x9C, mode: OpMode::ABX, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable}),
    0x9D => (Instruction::STA, InstructionInfo{opcode: 0x9D, mode: OpMode::ABX, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0x9E => (Instruction::SHX, InstructionInfo{opcode: 0x9E, mode: OpMode::ABY, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable}),
    0x9F => (Instruction::AHX, InstructionInfo{opcode: 0x9F, mode: OpMode::ABY, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalUnstable}),

    0xA0 => (Instruction::LDY, InstructionInfo{opcode: 0xA0, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA1 => (Instruction::LDA, InstructionInfo{opcode: 0xA1, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA2 => (Instruction::LDX, InstructionInfo{opcode: 0xA2, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA3 => (Instruction::LAX, InstructionInfo{opcode: 0xA3, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xA4 => (Instruction::LDY, InstructionInfo{opcode: 0xA4, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA5 => (Instruction::LDA, InstructionInfo{opcode: 0xA5, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA6 => (Instruction::LDX, InstructionInfo{opcode: 0xA6, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA7 => (Instruction::LAX, InstructionInfo{opcode: 0xA7, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xA8 => (Instruction::TAY, InstructionInfo{opcode: 0xA8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xA9 => (Instruction::LDA, InstructionInfo{opcode: 0xA9, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xAA => (Instruction::TAX, InstructionInfo{opcode: 0xAA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xAB => (Instruction::LAX, InstructionInfo{opcode: 0xAB, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalHighlyUnstable}),
    0xAC => (Instruction::LDY, InstructionInfo{opcode: 0xAC, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xAD => (Instruction::LDA, InstructionInfo{opcode: 0xAD, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xAE => (Instruction::LDX, InstructionInfo{opcode: 0xAE, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xAF => (Instruction::LAX, InstructionInfo{opcode: 0xAF, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0xB0 => (Instruction::BCS, InstructionInfo{opcode: 0xB0, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xB1 => (Instruction::LDA, InstructionInfo{opcode: 0xB1, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xB2 => (Instruction::KIL, InstructionInfo{opcode: 0xB2, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xB3 => (Instruction::LAX, InstructionInfo{opcode: 0xB3, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0xB4 => (Instruction::LDY, InstructionInfo{opcode: 0xB4, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xB5 => (Instruction::LDA, InstructionInfo{opcode: 0xB5, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xB6 => (Instruction::LDX, InstructionInfo{opcode: 0xB6, mode: OpMode::ZPY, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xB7 => (Instruction::LAX, InstructionInfo{opcode: 0xB7, mode: OpMode::ZPY, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xB8 => (Instruction::CLV, InstructionInfo{opcode: 0xB8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xB9 => (Instruction::LDA, InstructionInfo{opcode: 0xB9, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xBA => (Instruction::TSX, InstructionInfo{opcode: 0xBA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xBB => (Instruction::LAS, InstructionInfo{opcode: 0xBB, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0xBC => (Instruction::LDY, InstructionInfo{opcode: 0xBC, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xBD => (Instruction::LDA, InstructionInfo{opcode: 0xBD, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xBE => (Instruction::LDX, InstructionInfo{opcode: 0xBE, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xBF => (Instruction::LAX, InstructionInfo{opcode: 0xBF, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),

    0xC0 => (Instruction::CPY, InstructionInfo{opcode: 0xC0, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC1 => (Instruction::CMP, InstructionInfo{opcode: 0xC1, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC2 => (Instruction::NOP, InstructionInfo{opcode: 0xC2, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xC3 => (Instruction::DCP, InstructionInfo{opcode: 0xC3, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xC4 => (Instruction::CPY, InstructionInfo{opcode: 0xC4, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC5 => (Instruction::CMP, InstructionInfo{opcode: 0xC5, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC6 => (Instruction::DEC, InstructionInfo{opcode: 0xC6, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC7 => (Instruction::DCP, InstructionInfo{opcode: 0xC7, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xC8 => (Instruction::INY, InstructionInfo{opcode: 0xC8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xC9 => (Instruction::CMP, InstructionInfo{opcode: 0xC9, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xCA => (Instruction::DEX, InstructionInfo{opcode: 0xCA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xCB => (Instruction::AXS, InstructionInfo{opcode: 0xCB, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xCC => (Instruction::CPY, InstructionInfo{opcode: 0xCC, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xCD => (Instruction::CMP, InstructionInfo{opcode: 0xCD, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xCE => (Instruction::DEC, InstructionInfo{opcode: 0xCE, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xCF => (Instruction::DCP, InstructionInfo{opcode: 0xCF, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0xD0 => (Instruction::BNE, InstructionInfo{opcode: 0xD0, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xD1 => (Instruction::CMP, InstructionInfo{opcode: 0xD1, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xD2 => (Instruction::KIL, InstructionInfo{opcode: 0xD2, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xD3 => (Instruction::DCP, InstructionInfo{opcode: 0xD3, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xD4 => (Instruction::NOP, InstructionInfo{opcode: 0xD4, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xD5 => (Instruction::CMP, InstructionInfo{opcode: 0xD5, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xD6 => (Instruction::DEC, InstructionInfo{opcode: 0xD6, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xD7 => (Instruction::DCP, InstructionInfo{opcode: 0xD7, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xD8 => (Instruction::CLD, InstructionInfo{opcode: 0xD8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xD9 => (Instruction::CMP, InstructionInfo{opcode: 0xD9, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xDA => (Instruction::NOP, InstructionInfo{opcode: 0xDA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xDB => (Instruction::DCP, InstructionInfo{opcode: 0xDB, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xDC => (Instruction::NOP, InstructionInfo{opcode: 0xDC, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0xDD => (Instruction::CMP, InstructionInfo{opcode: 0xDD, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xDE => (Instruction::DEC, InstructionInfo{opcode: 0xDE, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xDF => (Instruction::DCP, InstructionInfo{opcode: 0xDF, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0xE0 => (Instruction::CPX, InstructionInfo{opcode: 0xE0, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE1 => (Instruction::SBC, InstructionInfo{opcode: 0xE1, mode: OpMode::IZX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE2 => (Instruction::NOP, InstructionInfo{opcode: 0xE2, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xE3 => (Instruction::ISC, InstructionInfo{opcode: 0xE3, mode: OpMode::IZX, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xE4 => (Instruction::CPX, InstructionInfo{opcode: 0xE4, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE5 => (Instruction::SBC, InstructionInfo{opcode: 0xE5, mode: OpMode::ZP, cycle: 3, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE6 => (Instruction::INC, InstructionInfo{opcode: 0xE6, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE7 => (Instruction::ISC, InstructionInfo{opcode: 0xE7, mode: OpMode::ZP, cycle: 5, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xE8 => (Instruction::INX, InstructionInfo{opcode: 0xE8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xE9 => (Instruction::SBC, InstructionInfo{opcode: 0xE9, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xEA => (Instruction::NOP, InstructionInfo{opcode: 0xEA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xEB => (Instruction::SBC, InstructionInfo{opcode: 0xEB, mode: OpMode::IMM, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xEC => (Instruction::CPX, InstructionInfo{opcode: 0xEC, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xED => (Instruction::SBC, InstructionInfo{opcode: 0xED, mode: OpMode::ABS, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xEE => (Instruction::INC, InstructionInfo{opcode: 0xEE, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xEF => (Instruction::ISC, InstructionInfo{opcode: 0xEF, mode: OpMode::ABS, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),

    0xF0 => (Instruction::BEQ, InstructionInfo{opcode: 0xF0, mode: OpMode::REL, cycle: 2, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xF1 => (Instruction::SBC, InstructionInfo{opcode: 0xF1, mode: OpMode::IZY, cycle: 5, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xF2 => (Instruction::KIL, InstructionInfo{opcode: 0xF2, mode: OpMode::IMP, cycle: 0, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xF3 => (Instruction::ISC, InstructionInfo{opcode: 0xF3, mode: OpMode::IZY, cycle: 8, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xF4 => (Instruction::NOP, InstructionInfo{opcode: 0xF4, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xF5 => (Instruction::SBC, InstructionInfo{opcode: 0xF5, mode: OpMode::ZPX, cycle: 4, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xF6 => (Instruction::INC, InstructionInfo{opcode: 0xF6, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xF7 => (Instruction::ISC, InstructionInfo{opcode: 0xF7, mode: OpMode::ZPX, cycle: 6, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xF8 => (Instruction::SED, InstructionInfo{opcode: 0xF8, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xF9 => (Instruction::SBC, InstructionInfo{opcode: 0xF9, mode: OpMode::ABY, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xFA => (Instruction::NOP, InstructionInfo{opcode: 0xFA, mode: OpMode::IMP, cycle: 2, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xFB => (Instruction::ISC, InstructionInfo{opcode: 0xFB, mode: OpMode::ABY, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable}),
    0xFC => (Instruction::NOP, InstructionInfo{opcode: 0xFC, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::IllegalStable}),
    0xFD => (Instruction::SBC, InstructionInfo{opcode: 0xFD, mode: OpMode::ABX, cycle: 4, cycle_inc_pbc: true, legality: LegalityType::Legal}),
    0xFE => (Instruction::INC, InstructionInfo{opcode: 0xFE, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::Legal}),
    0xFF => (Instruction::ISC, InstructionInfo{opcode: 0xFF, mode: OpMode::ABX, cycle: 7, cycle_inc_pbc: false, legality: LegalityType::IllegalStable }),
  }
}
